### ISSUE TITLE
panics with a nil pointer dereference

### ISSUE THREAD

**Issue by cgonyeo** [taskcluster/jsonschema2go#8]
```
derek@proton 1 ~/go/src/github.com/coreos/ignition/schema> cat ignition.json | jsonschema2go -o schema
Unknown scheme: ''
URL: '{#'
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x482b3c]

goroutine 1 [running]:
panic(0x6c2fc0, 0xc420010110)
	/nix/store/1blrc2bxdfjrk3kl46l75dw4i1lpswp5-go-1.7.1/share/go/src/runtime/panic.go:500 +0x1a1
github.com/taskcluster/jsonschema2go.(*Job).loadJsonSchema(0xc420014d80, 0xc4200f2b6a, 0x2, 0x0, 0x0, 0x0)
	/home/derek/go/src/github.com/taskcluster/jsonschema2go/jsonschema.go:579 +0x10c
github.com/taskcluster/jsonschema2go.(*Job).cacheJsonSchema(0xc420014d80, 0xc4200f24b2, 0x1, 0x0, 0xc42012f3b0, 0x0)
	/home/derek/go/src/github.com/taskcluster/jsonschema2go/jsonschema.go:607 +0x178
github.com/taskcluster/jsonschema2go.(*Job).Execute(0xc420014d80, 0xc420014d80, 0x200, 0xc4200e3f18)
	/home/derek/go/src/github.com/taskcluster/jsonschema2go/jsonschema.go:658 +0x209
main.main()
	/home/derek/go/src/github.com/taskcluster/jsonschema2go/jsonschema2go/cli.go:77 +0x226
```

I get this error when I try to give jsonschema2go my schema. Any clue how to fix this?

This is ignition.json, if it helps: http://lpaste.net/5721431062916104192

Oh also fwiw https://github.com/xeipuuv/gojsonschema ingests this json file without issue

**Comment by petemoore** [comment]
Hi @dgonyeo, apologies, I've only just seen this issue, I'll take a look!

**Comment by cgonyeo** [comment]
I ended up using schematyper for my project, so I don't need any fixes here anymore. By all means though, don't let that stop you from fixing something :)

**Comment by petemoore** [comment]
It looks like the problem is you are piping a json file, rather than piping a list of urls.
